### ISSUE TITLE
multiple recipient in bounce

### ISSUE THREAD

**Issue by aellert** [azumakuniyuki/bouncehammer#10]
it seems that bouncehammer only parse the first recipient in case there are multiple recipient.
I'm not skill enough to do the work but if you point me to the right direction to implement this functionnality, I could probably ask a friend for some help and provide a patch.

Many thanks for this great tool.

**Comment by azumakuniyuki** [comment]
Sisimai can solve this problem.
https://github.com/azumakuniyuki/p5-Sisimai
