### ISSUE TITLE
3 Records are skipped|no senderdomain

### ISSUE THREAD

**Issue by bradbakerdx** [azumakuniyuki/bouncehammer#13]
Running the following: /usr/local/bouncehammer/bin/databasectl --update --yesterday -vvvv I get the following output:

*debug1: Kanadzuchi/databasectl 2.7.13
 *debug1: Command started at Wed Jan  7 14:34:57 2015
 *debug1: Process ID = 4269
 *debug2: Pid file = /tmp/bouncehammer.1420659297.4269/databasectl.4269.pid
 *debug2: Operation = 12 [000000000000000000001100]
 *debug2: Temporary directory = /tmp/bouncehammer.1420659297.4269
 *debug1: Debug level = 3
 *debug1: Config name = Default
 *debug1: Config file = /usr/local/bouncehammer/etc/bouncehammer.cf
 *debug2: Connecting to the database
 *debug2: Database host = 127.0.0.1:3306
 *debug2: Database name = bouncehammer(MySQL)
 *debug2: Database user = bouncehammer
 *debug2: Using table = BounceLogs
 *debug1: Log file(date) = 2015-01-06
(UPDATE|INSERT): 100% [==================================================================================================================================================]D 0h00m00s *debug2: Using table = DailyUpdates
 *debug2:     0 Records are successfully inserted
 *debug2:     0 Records are successfully updated
 *debug2:     3 Records are skipped|no senderdomain
 *debug2:     0 Records are skipped|older or same time stmap
 *debug2:     0 Records are skipped|reason is whitelisted
 *debug2:     0 Records are skipped|exceeds limit:0
 *debug2:     0 Records are failed to insert or update

Note where it says:
3 Records are skipped|no senderdomain

If I do a cat hammer.2015-01-06.log | grep senderdomain I see:
- { "addresser": "no-reply@ourdomain.org", "bounced": "1420576813", "description": { "deliverystatus": "5.1.1", "diagnosticcode": "smtp; 550-5.1.1 The email account that you tried to reach does not exist. Please try 550-5.1.1 double-checking the recipients email address for typos or 550-5.1.1 unnecessary spaces. Learn more at 550 5.1.1 http://support.google.com/mail/bin/answer.py?answer=6596 if11si858342igb.55 - gsmtp", "listid": "", "messageid": "<20150106204013.EBEFB80BDCFB@smtp2.ourdomain.org>", "smtpagent": "unknown", "subject": "Test email", "timezoneoffset": "+0000" }, "destination": "ourdomain.org", "frequency": 1, "hostgroup": "pc", "provider": "various", "reason": "userunknown", "recipient": "bab5470-foo1@ourdomain.org", "senderdomain": "ourdomain.org","token": "1af89b2c6bd10306bf308ec8f6170c98" }

- { "addresser": "no-reply@ourdomain.org", "bounced": "1420576815", "description": { "deliverystatus": "5.1.1", "diagnosticcode": "smtp; 550-5.1.1 The email account that you tried to reach does not exist. Please try 550-5.1.1 double-checking the recipients email address for typos or 550-5.1.1 unnecessary spaces. Learn more at 550 5.1.1 http://support.google.com/mail/bin/answer.py?answer=6596 o5si42085056icm.77 - gsmtp", "listid": "", "messageid": "<20150106204015.AA8BA80CC96B@smtp2.ourdomain.org>", "smtpagent": "unknown", "subject": "Test email", "timezoneoffset": "+0000" }, "destination": "ourdomain.org", "frequency": 1, "hostgroup": "pc", "provider": "various", "reason": "userunknown", "recipient": "bab5470-foo2@ourdomain.org", "senderdomain": "ourdomain.org","token": "f08a17c6a7a133319cb229949d012f23" }

- { "addresser": "no-reply@ourdomain.org", "bounced": "1420576940", "description": { "deliverystatus": "5.1.1", "diagnosticcode": "smtp; 550-5.1.1 The email account that you tried to reach does not exist. Please try 550-5.1.1 double-checking the recipients email address for typos or 550-5.1.1 unnecessary spaces. Learn more at 550 5.1.1 http://support.google.com/mail/bin/answer.py?answer=6596 bf7si2031icc.32 - gsmtp", "listid": "", "messageid": "<20150106204220.D9FF180CDA2A@smtp2.ourdomain.org>", "smtpagent": "unknown", "subject": "Test email", "timezoneoffset": "+0000" }, "destination": "ourdomain.org", "frequency": 1, "hostgroup": "pc", "provider": "various", "reason": "userunknown", "recipient": "bab5470-sdf@ourdomain.org", "senderdomain": "ourdomain.org", "token": "2b07a511e7bb0a9121c6ff7fabe50153" }

The sender domain does seem to be set to ourdomain.org. So I'm not sure why databasectl see's the senderdomain as empty? This is preventing records from being added to the database.

Thanks
Brad

**Comment by azumakuniyuki** [comment]
The value of "senderdomain" must exist on t_senderdomain table before executing bin/databasectl command. Would you make sure that "ourdomain.org" has been registered in the table using the following command?

```
% /usr/local/bouncehammer/bin/tablectl -ts --list
- { "id": 1, "domainname": "cubicroot.jp", "description": "Cubicroot Co. Ltd.", "disabled": 0 }
- { "id": 2, "domainname": "bouncehammer.jp", "description": "", "disabled": 0 }
- { "id": 3, "domainname": "example.jp", "description": "", "disabled": 0 }
- { "id": 4, "domainname": "example.org", "description": "", "disabled": 0 }
```
Information about senderdomain for databasectl command is available at http://bouncehammer.jp/en/v2/docs/config/sys/insert-into .

**Comment by bradbakerdx** [comment]
That was the issue! Thank You!! I absolutely missed the step when setting up bouncehammer.

**Comment by azumakuniyuki** [comment]
Thanks for using bouncehammer !
