### ISSUE TITLE
MailboxParser not Truncating

### ISSUE THREAD

**Issue by bradbakerdx** [azumakuniyuki/bouncehammer#14]
I'm running the following command to parse mail in a postfix mailbox file under /var/mail/bounce:
mailboxparser -g --log /var/mail/bounce --truncate

The command runs, and the mail is parsed but the mailbox file is not truncated which I thought what --truncate was supposed to do. Here's what I see in verbose mode:

/usr/local/bouncehammer/bin/mailboxparser -g --log /var/mail/bounce --truncate -vvvv
 *debug1: Kanadzuchi/mailboxparser 2.7.13
 *debug1: Command started at Fri Jan  9 09:28:22 2015
 *debug1: Process ID = 7551
 *debug2: Pid file = /tmp/bouncehammer.1420813702.7551/mailboxparser.7551.pid
 *debug2: Operation = 300 [000000000000000100101100]
 *debug2: Temporary directory = /tmp/bouncehammer.1420813702.7551
 *debug1: Debug level = 3
 *debug1: Config name = Default
 *debug1: Config file = /usr/local/bouncehammer/etc/bouncehammer.cf
 *debug2: Max size of each chunk = 1048576 bytes
 *debug2: Size of all mailboxes = 0 bytes
 *debug1: Log directory = /usr/local/bouncehammer/var/spool
 *debug1: Temporary log = /usr/local/bouncehammer/var/spool/hammer.2015-01-09.54afe586.001d84.tmp
Seek mailboxes: 100% [================================================================================================================================================================]D 0h00m00s *debug0: Parsed emails/bounces(ratio) in the mailbox = 0/0 (0.0000)

Then I do a cat on the mailbox file:
cat /var/mail/bounce | grep -c "Message-Id:"
10

So clearly you can see there is email still in the /var/mail/bounce. Why isn't the mailbox being truncated?

Thanks
Brad

**Comment by bradbakerdx** [comment]
I created a test script: 
#!/usr/bin/perl
open FILE, ">", "/var/mail/bounce" or die $!;
truncate( $FILE, 0 );

That DOES truncate the file so I'm not sure why it's not working in bouncehammer. Is there anything else I can check or some way to debug what's happening?

Thanks
Brad

**Comment by bradbakerdx** [comment]
I don't understand why - but now this seems to be suddenly working. I don't understand what I did. I guess we can close this up.

**Comment by azumakuniyuki** [comment]
I've tried to parse with --truncate option like the following command:
```
% ls -1 > /tmp/mbox
% ls -l /tmp/mbox
-rw-r--r--  1 ak  wheel  205 Jan 10 14:31 /tmp/mbox
% /usr/local/bouncehammer/bin/mailboxparser -Tv --truncate /tmp/mbox -vvvvvvv
 *debug1: Kanadzuchi/mailboxparser 2.7.13
 *debug1: Command started at Sat Jan 10 14:31:35 2015
 *debug1: Process ID = 16407
 *debug2: Pid file = /tmp/mailboxparser.16407.pid
 *debug2: Operation = 38 [000000000000000000100110]
 *debug2: Temporary directory = /tmp/bouncehammer.1420867895.16407
 *debug1: Debug level = 7
 *debug1: Config name = Test Run
 *debug1: Config file = /dev/null
 *debug2: Max size of each chunk = 1048576 bytes
 *debug2: Size of all mailboxes = 205 bytes                                                                                                                     
Parse mailboxes(1): 100% [===========================================================================================================================]D 0h00m00s *debug0: Parsed emails/bounces(ratio) in the mailbox = 0/0 (0.0000)
% ls -l /tmp/mbox
-rw-r--r--  1 ak  wheel  0 Jan 10 14:31 /tmp/mbox
```

I made sure that the mailbox has been truncated.
